export { default as Blog } from './blog/Blog'
export { default as Features } from './products/Products'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as WhatBotanic } from './whatBotanic/WhatBotanic'